version: "1.0.0"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: lockbio
    ports:
      - 5432:5432

  db-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9090:80
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin